### ISSUE TITLE
Baysor0.7.1 output for XeniumRanger 

### ISSUE THREAD

**Issue by alextsoi1** [kharchenkolab/Baysor#148]
Hi , when using the output from the latest version of baysor (0.7.1) to run Xenium Ranger, we encounter the following errors. We have tried both the GeometryCollectionLegacy or FeatureCollection formats, each gives a slightly different error message. We checked with 10X, and understand they are going to push an updated XR soon, but would want to share this in case there is any way to get around now. Thx!

xeniumranger import-segmentation --id=baysor \
                                 --xenium-bundle=output-XETG00077__0040181__11774-JF-1_ROI_A1__20241028__162950/ \
                                 --transcript-assignment=segmentation.csv \
                                 --viz-polygons=segmentation_polygons_2d.json \
                                 --units=microns \
                                 --localcores=16 \
                                 --localmem=128
                                 
### error when using GeometryCollectionLegacy:
```Traceback (most recent call last):
  File "/Software/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 648, in _main
    stage.main()
  File "/Software/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 617, in main
    self._run(
  File "/Software/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 564, in _run
    cmd()
  File "/Software/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 618, in <lambda>
    lambda: self._module.join(args, outs, chunk_defs, chunk_outs)
  File "/Software/xeniumranger-xenium3.0/mro/insitu/stages/xr_import_transcripts/__init__.py", line 97, in join
    import_transcript_assignments.join(
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/stages/import_transcript_assignments.py", line 69, in j>
    results = import_baysor_transcript_assignments(
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/import_transcripts.py", line 95, in>
    ) = baysor_results.generate_cell_segmentation_dataset(
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/baysor.py", line 787, in generate_c>
    return self._generate_cell_segmentation_dataset_faithful(
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/baysor.py", line 639, in _generate_>
    simplified_polygons, num_vertices = baysor_polygons.simplify_polygons(
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/geojson.py", line 276, in simplify_>
    n = simplify_polygon(old_polygon, max_vs, simplify_epsilon, new_polygon)
TypeError: argument 'verts': dimensionality mismatch:
 from=1, to=2
 ```
 
 ### error when using Feature Collection
 ```
 Traceback (most recent call last):
  File "/Software/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 648, in _main
    stage.main()
  File "/Software/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 617, in main
    self._run(
  File "/Software/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 564, in _run
    cmd()
  File "/Software/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 618, in <lambda>
    lambda: self._module.join(args, outs, chunk_defs, chunk_outs)
  File "/Software/xeniumranger-xenium3.0/mro/insitu/stages/xr_import_transcripts/__init__.py", line 97, in join
    import_transcript_assignments.join(
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/stages/import_transcript_assignments.py", line 69, in join
    results = import_baysor_transcript_assignments(
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/import_transcripts.py", line 84, in import_baysor_transcript_assignments
    baysor_results = BaysorSegmentationResults.deserialize(
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/baysor.py", line 374, in deserialize
    polygons = BaysorSegmentationPolygons.deserialize(polygons_path)
  File "/Software/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/baysor.py", line 279, in deserialize
    geometries = data["geometries"]
KeyError: 'geometries'
 ```

**Comment by mattcai10x** [comment]
Hello from 10x, for anyone who runs into the same error when using GeometryCollectionLegacy I want to announce that [Xenium Ranger 3.1](https://www.10xgenomics.com/support/software/xenium-ranger/downloads) resolved the compatibility issues between Xenium Ranger and Baysor v0.7. To ensure smooth operation, please use Baysor v0.7.1 with the --polygon-format=GeometryCollectionLegacy option and Xenium Ranger v3.1. Note that Xenium Ranger does not yet support the FeatureCollection format for importing Baysor results.

**Comment by sbamopoulos** [comment]
For future reference: I was able to run xenium ranger 4.0 on the Baysor v0.7.1. output with the default --polygon-format ("FeatureCollection"), so the compatibility issues should be resolved.
